blank_issues_enabled: false
contact_links:
  - name: 🫶 Support portal
    about: Get support using through our support website.
    url: https://support.bbsmc.org.cn
  - name: 💬 Chat on Discord
    about: Join our Discord server to chat about Bbsmc.
    url: https://discord.bbsmc.org.cn
